<?php

/**
 * @file
 * User display name module file.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function user_display_name_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  if ($route_name === 'help.page.user_display_name') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t("This module adds a display name field to user entities to use instead of the username when displaying the user's name.") . '</p>';

  }
  return $output;
}

/**
 * Implements hook_entity_base_field_info().
 */
function user_display_name_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'user') {
    $fields['display_name'] = BaseFieldDefinition::create('string')
      ->setName('display_name')
      ->setTargetEntityTypeId($entity_type->id())
      ->setTargetBundle(NULL)
      ->setProvider('user_display_name')
      ->setLabel(t('Display Name'))
      ->setDescription(t('Preferred display name.'))
      ->setRevisionable($entity_type->isRevisionable())
      ->setTranslatable(TRUE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'text_textfield',
        'weight' => -1,
      ]);
  }
  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form() for user entities.
 */
function user_display_name_user_prepare_form(UserInterface $user, $operation, FormStateInterface $form_state) {
  // Set the display name to the user name if empty.
  if (empty($user->display_name->value)) {
    $user->set('display_name', (string) $user->label());
  }
}

/**
 * Implements hook_user_format_name_alter().
 */
function user_display_name_user_format_name_alter(&$name, AccountInterface $account) {
  if (!empty($account->display_name->value)) {
    $name = $account->display_name->value;
  }
}
